### PR TITLE
ci-setup: refactor working-directory

### PR DESCRIPTION
**Pull request by rm98**
## Pull Request Checklist

Please ensure that you have completed the following tasks:

- [x] Updated the changelog.
- [x] Updated all relevant `*.md` files in `docs`.

After merging to the `master` branch, ensure that you [update the gh-pages branch](https://github.com/polaris-slo-cloud/polaris#maintaining-gh-pages).

Hi!
I've updated the CI setup slightly to make use of [defaults.run](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun) so that the working-directory only needs to be set once.

### CODE REVIEW

**Review by tommazzo89 — APPROVED** [review]
This greatly reduces the redundancy within the `polaris-ci.yml` file. Thanks a lot!

**Review by tommazzo89 — CHANGES_REQUESTED** [review]
I just saw that the `build` job has failed. Can you please take another look at that?

**Comment by rm98** [comment]
Hi! Just saw that too.
It seems like this doesn't work as expected (although it's basically the same as the example from the documentation).
Will investigate it.

**Review by tommazzo89 — APPROVED** [review]
Great! Thanks a lot for your contribution!

**Pull request merged**
